name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Build esrum documentation
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "esrum/"

    # Publish built docs to gh-pages branch
    - name: Commit documentation changes
      run: |
        git clone https://github.com/cbmrphenomics/cbmrphenomics.github.io.git --branch gh-pages --single-branch gh-pages
        rsync -a --checksum --delete --exclude '.*' --exclude /esrum root/ gh-pages/
        rsync -a --checksum --delete --exclude '.*' esrum/build/html/ gh-pages/esrum/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        # Ignore failure due to lack of changes
        git commit -m "Update documentation" -a || true

    # Push changes to gh-pages
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
