name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: ./.github/workflows/pre-commit.yaml

  publish:
    name: Publish to https://cbmr-data.github.io
    needs: pre-commit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Build esrum documentation
      - uses: ammaraskar/sphinx-action@c61ac11d9ee097caf8983c10c8b5af5861b32b54 # master (2024-09-09)
        with:
          docs-folder: "esrum/"

      # Publish built docs to gh-pages branch
      - name: Commit documentation changes
        run: |
          git clone https://github.com/cbmr-data/cbmr-data.github.io.git --branch gh-pages --single-branch gh-pages
          rsync -a --checksum --delete --exclude '.*' --exclude /esrum root/ gh-pages/
          rsync -a --checksum --delete --exclude '.*' esrum/build/html/ gh-pages/esrum/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # Ignore failure due to lack of changes
          git commit -m "Update documentation" -a || true

      # Push changes to gh-pages
      - name: Push changes
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # master (2024-07-01)
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
